[[bond]]
source = "tpknam1qp2jtx5x30vhfxul6vdk8xljgfhudgel69tvau4fu96lxscse9rfgdha4ur"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "108"

[bond.signatures]
tpknam1qp2jtx5x30vhfxul6vdk8xljgfhudgel69tvau4fu96lxscse9rfgdha4ur = "signam1qq674pl7pp0x4j5nry43cr75407akz7c4sth5k4pjhsxv4mezlerw2y0m4p0hzn3dtr7vks586hrlet5ldt82pn74vafdvkguq39e0gdxl60p9"


[[bond]]
source = "tpknam1qp2jtx5x30vhfxul6vdk8xljgfhudgel69tvau4fu96lxscse9rfgdha4ur"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "26"

[bond.signatures]
tpknam1qp2jtx5x30vhfxul6vdk8xljgfhudgel69tvau4fu96lxscse9rfgdha4ur = "signam1qpypy02reychyjye36t7sx2qd5j0y7zye5atacmlex9pakyhq7tppwlntty9g8m7q2pf0vtp7k0rj0a9w0tx5t3nv92vhruan84rnxsqmpl097"
